const desafios = [
  "Beije por 1 minuto direto ainda essa semana",
  "Converse por 5 minutos sem usar apelidos carinhosos — só o nome real",
  "Envie uma mensagem só com emojis, sem texto, que signifique “eu te amo”",
  "Marque um jantar onde só pode falar frases começando com “Meu / Minha querido(a) [apelido engraçado]…”",
  "Durante uma chamada, faça caretas toda vez que o outro usar apelido",
  "Por 1 hora, só pode responder com gifs ou figurinhas",
  "No próximo encontro, só pode se referir ao outro como personagem de desenho animado que escolherem",
  "Descubra hoje qual é o carro dos sonhos do outro, sem perguntar diretamente",
  "Descubra hoje a cor da casa ideal do outro, sem perguntar diretamente",
  "Descubra hoje o prato favorito do outro num almoço em família, só pelas dicas",
  "Descubra hoje a rotina perfeita de sábado em família do outro, sem perguntar direto",
  "Descubra hoje a música que o outro escolheria para tocar num momento em família",
  "Descubra hoje o hobby ideal para fazer em casa, só pelas pistas",
  "Descubra hoje o lugar onde gostaria de morar, sem perguntar diretamente",
  "Descubra hoje um detalhe engraçado que o outro quer ter na cozinha da futura casa",
  "Descubra hoje o presente ideal para a casa do outro, só pelas dicas que der",
  "Descubra hoje uma meta engraçada para alcançar até os 30 anos, só pelos emojis que usar",
  "Descubra hoje qual comida o outro tentaria cozinhar para surpreender a família",
  "Descubra hoje a viagem ideal em família do outro, só pelo que comentar",
  "Descubra hoje a brincadeira favorita para fazer com filhos, só pelo jeito que contar",
  "Descubra hoje o nome engraçado que daria para o cachorro da família",
  "Descubra hoje qual comida acha que o outro ama, só pelas pistas que deixar escapar",
  "Descubra hoje qual celular dos sonhos do outro, só pelas descrições",
  "Descubra hoje o prato ideal para um jantar especial, só pelas dicas",
  "Faça um áudio de 30 segundos contando uma história rimando",
  "Durante o próximo encontro, toda vez que o outro rir, imite um som engraçado escolhido",
  "No próximo vídeo que mandar, só pode usar voz de personagem famoso",
  "Durante 10 minutos, só pode falar em perguntas, sem afirmar nada",
  "Só pode dar abraço se falar a palavra “super-herói” antes",
  "Toda vez que o outro mandar mensagem hoje, responda com apelido novo inventado na hora",
  "Por um dia, só chame o outro por um apelido baseado em comida favorita",
  "Faça um “vale um beijo” com um desafio engraçado para cumprir antes",
  "Só pode usar sotaque de um país escolhido pelo outro durante uma conversa",
  "Conte uma piada usando só palavras que comecem com a mesma letra",
  "No jantar, toda vez que o outro pedir algo, responda com um elogio novo",
  "Ao se despedir no próximo encontro, use uma frase de música cristã que gostam",
  "Envie um áudio rindo por 10 segundos",
  "Conte uma piada ruim e aguente a reação",
  "Mande uma foto fazendo careta",
  "Prepare um presente simples para entregar no próximo encontro",
  "Faça um elogio inesperado sobre algo recente",
  "Conte um mico que nunca contou para ninguém",
  "Diga “amor” três vezes sem sorrir e envie áudio",
  "Mande um meme interno que só vocês entendem",
  "Crie um apelido engraçado e use no próximo encontro",
  "Faça um desenho simples do outro e entregue pessoalmente",
  "Marque uma chamada para cantar um trecho juntos",
  "Diga qual superpoder teria e façam uma brincadeira com isso",
  "Mande uma foto com zoom exagerado em algo bobo do lugar onde estiver",
  "Conte um segredo engraçado pessoalmente",
  "Envie um áudio dizendo “Você é minha pessoa favorita” com voz dramática",
  "Conte o que faria se ganhasse na loteria e planejem juntos",
  "Reservem um momento para orar juntos, presencial ou por chamada",
  "Envie uma playlist para ouvirem quando estiverem longe",
  "Conte um sonho estranho e riam juntos depois",
  "Marque um rolê em cafeteria",
  "Compartilhe uma palavra nova que aprendeu",
  "Marque um filme ou série para assistirem juntos",
  "Conte o pior presente que já recebeu e riam juntos",
  "Faça um “vale massagem” para o próximo encontro",
  "Conte uma situação constrangedora e faça rir",
  "Mande uma foto de algo que lembre o outro",
  "Desenhe o que acha que o outro está fazendo agora e mande",
  "Marque um desafio do silêncio de 10 minutos só de zoeira",
  "Diga 3 coisas que faria se tivesse um clone",
  "Marque uma noite para jogar algo online",
  "Mande uma foto com cara de surpresa exagerada",
  "Marque um cinema para assistir algo aleatório juntos",
  "Envie áudio cantando “Parabéns” errado de propósito",
  "Conte algo que te dá vergonha, mas adora fazer",
  "Diga a última vez que chorou",
  "Faça uma chamada rápida só para dizer “eu te amo”",
  "Conte a primeira coisa que fez no dia sem esconder nada",
  "Conte um talento secreto, mesmo que inútil",
  "Desenhe o lugar onde se conheceram e mostre",
  "Envie um áudio com uma bênção para a semana do outro",
  "Pergunte a última vez que se sentiu feliz de verdade",
  "Faça um “vale presente surpresa” para o próximo encontro",
  "Marque um piquenique ou café juntos",
  "Conte uma palavra que resume seu humor hoje",
  "Mande uma foto do cantinho favorito do outro",
  "Diga a primeira coisa que faria se pudesse viajar no tempo",
  "Conte algo que não gosta, mas faria por amor",
  "Mande uma música com a legenda: “Essa seria a trilha sonora de hoje com você”",
  "Descreva como seria um filme sobre o relacionamento de vocês",
  "Mande um print antigo que te lembre o começo da relação",
  "Escreva 3 qualidades do outro que você não elogia com frequência",
  "Pergunte: “Se nosso amor fosse uma estação do ano, qual seria?”",
  "Poste uma indireta fofa só para o outro entender",
  "Marque uma chamada para jogarem 'eu nunca' versão casal",
  "Tire uma foto com o que tiver na sua frente e diga: “Isso tem tudo a ver com a gente porque…”",
  "Envie uma palavra inventada que descreve vocês dois",
  "Marque um momento da semana para ficar em silêncio juntos por chamada",
  "Mande um áudio sussurrando algo romântico",
  "Escreva uma legenda de Instagram como se estivessem em 2040",
  "Mande um 'tutorial de como me amar' em passos engraçados",
  "Compartilhe o que faria diferente se tivesse te conhecido antes",
  "Diga o que mais te acalma no outro",
  "Mande um “vale abraço em silêncio” para o próximo encontro",
  "Conte uma memória favorita que viveu com o outro em detalhes",
  "Escreva uma carta como se estivesse longe há 1 ano",
  "Grave um áudio contando uma novidade fingida só para brincar",
  "Faça um elogio que comece com cada letra do nome do outro"
];

function mostrarDesafio(pessoa) {
   const hoje = new Date();
   const dia = hoje.getDate();
   const mes = hoje.getMonth() + 1;
   const ano = hoje.getFullYear();
   const seedSamuel = (dia + mes + ano) % desafios.length;
   const seedSara = (dia * mes + ano) % desafios.length;
   const indexSamuel = seedSamuel;
   let indexSara = seedSara;
   if (indexSamuel === indexSara) {
     indexSara = (indexSara + 1) % desafios.length;
   }
   if (pessoa === 'Samuel') {
     document.getElementById('textoSamuel').textContent = desafios[indexSamuel];
   } else if (pessoa === 'Sara') {
     document.getElementById('textoSara').textContent = desafios[indexSara];
   }
}